### ISSUE TITLE
The login via GitHub option is disabled

### ISSUE THREAD

**Issue by n-d-r-d-g** [Front-End-Coders-Mauritius/frontend.mu#147]
**Issue:**
Currently, I cannot choose to login via GitHub as the button is disabled.

![image](https://github.com/user-attachments/assets/0f59edf3-e569-4034-baee-8a8bd0e27f21)

Not sure if this feature is in progress or just not working on my end. I tried it on Firefox, Chromium and Brave and it's disabled on all of them.

**Expected:**
It would be nice to enable the login via GitHub feature. Also, are there any plans to implement a custom login, i.e. not via SSO? @MrSunshyne 

Glad to assist on this if you need help ✌️.

**Comment by MrSunshyne** [comment]
It's currently disabled because it is not yet implemented. We plan to add it as some people do not use Google.

We chose to not have custom login as a way to avoid 'fake' accounts. Ideally a login associated with a phone number would work best for us, but i'm not sure how to do that ! Let's keep discussing

**Comment by n-d-r-d-g** [comment]
Alright, I'll think about it.

Regarding the login via GitHub option, I'd be happy to help out.

Let me know.
